### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by timseries** [tinkerpop/rexster#385]
Hi, thank you for all of the great work and making this available. Having just gotten familiar with Rexster and successfully completed an OrientDB installation, I would like to point out some confusing issues with the docs here:
https://github.com/tinkerpop/rexster/wiki/Specific-Graph-Configurations#orientdb

1. "local" should be "plocal", the "local" mode is no longer supported by the latest release of OrientDb.
2. I found that I had to copy ALL of the OrientDb jars to the ext folder form the OrientDb folder. If possible, could you please indicate which `/ext` folder? There are two within rexster-server (one in `/source`, one in `/target`). I think the safest bet is to copy to the one located in target if installation has already been performed, and to copy to the one located in . 
3. The statement "TinkerPop does not officially support remote connections to OrientDB." ...what does this mean exactly? I was able to get a connection from Rexster to OrientDB using remote mode fine.

I will raise a separate issue with the OrientDB github repository regarding the conflicting docs. Perhaps the best solution would be to communicate with Luca etc and decide upon a place where a single setup guide should exist. Both projects Rexster/OrientDB claim interoperability with the other...it shouldn't be this difficult to get them to work together.

Thanks!

**Comment by spmallette** [comment]
I changed "local" to "plocal".    The docs typically refer to the `ext` directory as `$REXSTER_HOME/ext`.  Is that not explicit enough or did you see it not referred to that way somewhere?

there used to be problems with connections using "remote:" in orientdb.  i guess there aren't such issues anymore since you aren't seeing problems...i've removed that limitation.

i think that OrientDB docs should hold the "official" rexster configuration - I'm happy to link to it from here: https://github.com/tinkerpop/rexster/wiki/Specific-Graph-Configurations#orientdb if a URL to that documentation is provided.

**Comment by timseries** [comment]
If that's agreeable to you, I've already offered to edit the orientdb docs, so it should be reflected in the wiki you've linked shortly.
